version: "2"

services:
  db:
    image: postgres:9.6
    container_name: postgres-tg
    environment:
      - "POSTGRES_USER=giftcard"
      - "POSTGRES_PASSWORD=14aD&LGbt=-J8h"
    volumes:
      - "postgresql:/var/lib/postgresql"
      - "postgresql_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  
  apache-php:
    image: php:7.0-apache
    container_name: apache-tg
    volumes:
      - ./giftcard-views/src/main/resources:/var/www/html
    ports:
      - 80:80

volumes:
  postgresql:
  postgresql_data:
